---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-acc-redhat-io-v1alpha1-agentcollective
  failurePolicy: Fail
  name: magentcollective.kb.io
  rules:
  - apiGroups:
    - acc.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - agentcollectives
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-acc-redhat-io-v1alpha1-agentcorpus
  failurePolicy: Fail
  name: magentcorpus.kb.io
  rules:
  - apiGroups:
    - acc.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - agentcorpora
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-acc-redhat-io-v1alpha1-agentcollective
  failurePolicy: Fail
  name: vagentcollective.kb.io
  rules:
  - apiGroups:
    - acc.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - agentcollectives
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-acc-redhat-io-v1alpha1-agentcorpus
  failurePolicy: Fail
  name: vagentcorpus.kb.io
  rules:
  - apiGroups:
    - acc.redhat.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - agentcorpora
  sideEffects: None
