"""Unit tests for acc.role_crd_loader (proposal 010 PR-3).

Covers the CRD → file projection path: the polling loop is exercised
indirectly via ``project_once()`` to keep tests deterministic; the
KubernetesCRDClient is not exercised here because it requires a live
cluster — covered separately by integration tests on acc1.
"""
from __future__ import annotations

import asyncio
from pathlib import Path
from typing import Any

import pytest

from acc.role_crd_loader import (
    RoleCRDProjector,
    _SENTINEL_HEADER,
    _strip_sentinel,
)


# ---------------------------------------------------------------------------
# FakeCRDClient — minimal Protocol impl for tests
# ---------------------------------------------------------------------------


class FakeCRDClient:
    """Stand-in for KubernetesCRDClient with hand-controlled state."""

    def __init__(self, collectives: list[dict[str, Any]] | None = None) -> None:
        self.collectives = collectives or []
        self.calls: list[str] = []  # records list_collectives invocations

    def list_collectives(self, namespace: str) -> list[dict[str, Any]]:
        self.calls.append(namespace)
        return list(self.collectives)  # defensive copy


# ---------------------------------------------------------------------------
# _strip_sentinel
# ---------------------------------------------------------------------------


class TestStripSentinel:
    def test_strips_comment_header(self):
        content = "# Header line 1\n# Header line 2\nrole_definition:\n  purpose: x\n"
        assert _strip_sentinel(content) == "role_definition:\n  purpose: x\n"

    def test_strips_blank_lines_in_header(self):
        content = "# header\n\n# more\nrole_definition: {}\n"
        assert _strip_sentinel(content) == "role_definition: {}\n"

    def test_no_header_returns_unchanged(self):
        content = "role_definition:\n  purpose: x\n"
        assert _strip_sentinel(content) == content

    def test_empty_input(self):
        assert _strip_sentinel("") == ""


# ---------------------------------------------------------------------------
# RoleCRDProjector.project_one
# ---------------------------------------------------------------------------


class TestProjectOne:
    def test_writes_role_file_on_first_call(self, tmp_path: Path):
        proj = RoleCRDProjector(
            roles_root=tmp_path,
            namespace="default",
            client=FakeCRDClient(),
        )
        written = proj.project_one("coding_agent", {
            "purpose": "Generate code",
            "persona": "analytical",
            "task_types": ["CODE_GENERATE"],
        })
        assert written is True
        target = tmp_path / "coding_agent" / "role.yaml"
        assert target.exists()
        body = target.read_text(encoding="utf-8")
        assert "Generated by acc.role_crd_loader" in body
        assert "role_definition:" in body
        assert "purpose: Generate code" in body
        assert "persona: analytical" in body
        assert "- CODE_GENERATE" in body

    def test_second_identical_call_is_noop(self, tmp_path: Path):
        proj = RoleCRDProjector(
            roles_root=tmp_path,
            namespace="default",
            client=FakeCRDClient(),
        )
        rd = {"purpose": "p", "persona": "concise"}
        assert proj.project_one("x", rd) is True
        # In-memory cache hit.
        assert proj.project_one("x", rd) is False

    def test_existing_file_with_same_body_is_noop(self, tmp_path: Path):
        """Operator restart: existing file matches → no rewrite."""
        proj = RoleCRDProjector(
            roles_root=tmp_path,
            namespace="default",
            client=FakeCRDClient(),
        )
        rd = {"purpose": "p", "persona": "concise"}
        assert proj.project_one("x", rd) is True

        # Simulate operator restart by constructing a fresh projector
        # so its _last_written cache is empty.
        proj2 = RoleCRDProjector(
            roles_root=tmp_path,
            namespace="default",
            client=FakeCRDClient(),
        )
        assert proj2.project_one("x", rd) is False

    def test_changed_content_triggers_rewrite(self, tmp_path: Path):
        proj = RoleCRDProjector(
            roles_root=tmp_path,
            namespace="default",
            client=FakeCRDClient(),
        )
        proj.project_one("x", {"purpose": "old"})
        assert proj.project_one("x", {"purpose": "new"}) is True
        body = (tmp_path / "x" / "role.yaml").read_text(encoding="utf-8")
        assert "purpose: new" in body
        assert "purpose: old" not in body

    def test_empty_role_definition_skipped(self, tmp_path: Path):
        proj = RoleCRDProjector(
            roles_root=tmp_path,
            namespace="default",
            client=FakeCRDClient(),
        )
        # All-None fields → cleaned dict is empty → no write.
        assert proj.project_one("x", {"purpose": None}) is False
        assert not (tmp_path / "x").exists()

    def test_atomic_write_uses_rename(self, tmp_path: Path):
        """Temp file should not survive after a successful write."""
        proj = RoleCRDProjector(
            roles_root=tmp_path,
            namespace="default",
            client=FakeCRDClient(),
        )
        proj.project_one("x", {"purpose": "p"})
        tmp_file = tmp_path / "x" / "role.yaml.tmp"
        assert not tmp_file.exists(), "atomic write should rename, not leave .tmp"

    def test_sentinel_includes_namespace_and_name(self, tmp_path: Path):
        proj = RoleCRDProjector(
            roles_root=tmp_path,
            namespace="acc-prod",
            client=FakeCRDClient(),
        )
        proj.project_one("coding_agent", {"purpose": "p"})
        body = (tmp_path / "coding_agent" / "role.yaml").read_text(encoding="utf-8")
        assert "acc-prod" in body
        assert "coding_agent" in body


# ---------------------------------------------------------------------------
# RoleCRDProjector.project_once (single polling cycle)
# ---------------------------------------------------------------------------


class TestProjectOnce:
    @pytest.mark.asyncio
    async def test_writes_all_collectives(self, tmp_path: Path):
        client = FakeCRDClient(collectives=[
            {"name": "alpha", "role_definition": {"purpose": "a", "persona": "concise"}},
            {"name": "beta",  "role_definition": {"purpose": "b", "persona": "formal"}},
        ])
        proj = RoleCRDProjector(tmp_path, "default", client)
        n = await proj.project_once()
        assert n == 2
        assert (tmp_path / "alpha" / "role.yaml").exists()
        assert (tmp_path / "beta" / "role.yaml").exists()

    @pytest.mark.asyncio
    async def test_skips_collectives_without_role_definition(self, tmp_path: Path):
        client = FakeCRDClient(collectives=[
            {"name": "alpha", "role_definition": {"purpose": "a"}},
            {"name": "beta",  "role_definition": None},
        ])
        proj = RoleCRDProjector(tmp_path, "default", client)
        n = await proj.project_once()
        assert n == 1
        assert (tmp_path / "alpha" / "role.yaml").exists()
        assert not (tmp_path / "beta").exists()

    @pytest.mark.asyncio
    async def test_client_exception_swallowed(self, tmp_path: Path):
        class BoomClient:
            def list_collectives(self, namespace: str) -> list[dict[str, Any]]:
                raise RuntimeError("API server unreachable")

        proj = RoleCRDProjector(tmp_path, "default", BoomClient())
        # Should not raise — projector logs and returns 0.
        n = await proj.project_once()
        assert n == 0

    @pytest.mark.asyncio
    async def test_idempotent_second_run_writes_nothing(self, tmp_path: Path):
        client = FakeCRDClient(collectives=[
            {"name": "alpha", "role_definition": {"purpose": "a"}},
        ])
        proj = RoleCRDProjector(tmp_path, "default", client)
        first = await proj.project_once()
        second = await proj.project_once()
        assert first == 1
        assert second == 0


# ---------------------------------------------------------------------------
# Polling lifecycle
# ---------------------------------------------------------------------------


class TestPollingLifecycle:
    @pytest.mark.asyncio
    async def test_start_and_stop(self, tmp_path: Path):
        client = FakeCRDClient(collectives=[
            {"name": "x", "role_definition": {"purpose": "p"}},
        ])
        proj = RoleCRDProjector(
            tmp_path, "default", client,
            poll_interval_s=0.05,
        )
        await proj.start()
        # Wait for at least one poll cycle.
        await asyncio.sleep(0.15)
        await proj.stop()
        assert (tmp_path / "x" / "role.yaml").exists()
        assert len(client.calls) >= 1

    @pytest.mark.asyncio
    async def test_start_idempotent(self, tmp_path: Path):
        client = FakeCRDClient()
        proj = RoleCRDProjector(tmp_path, "default", client, poll_interval_s=10)
        await proj.start()
        await proj.start()  # second call is a no-op
        await proj.stop()

    @pytest.mark.asyncio
    async def test_stop_without_start_is_safe(self, tmp_path: Path):
        proj = RoleCRDProjector(tmp_path, "default", FakeCRDClient())
        await proj.stop()  # should not raise


# ---------------------------------------------------------------------------
# Field translation (CRD camelCase → file snake_case)
# ---------------------------------------------------------------------------


class TestFieldTranslation:
    """Verify the FakeCRDClient round-trip mirrors what the real
    Kubernetes client produces — covered by reading the constant
    `_FIELD_MAP` indirectly via project_one rendering."""

    def test_camelcase_input_translated(self, tmp_path: Path):
        """When the caller already supplied snake_case keys, project
        them straight through.  (KubernetesCRDClient handles the
        camelCase→snake_case translation; tests inject snake_case
        directly to keep this module focused.)"""
        proj = RoleCRDProjector(tmp_path, "default", FakeCRDClient())
        proj.project_one("x", {
            "purpose": "p",
            "task_types": ["A"],
            "seed_context": "ctx",
            "category_b_overrides": {"token_budget": "2048"},
        })
        body = (tmp_path / "x" / "role.yaml").read_text(encoding="utf-8")
        assert "task_types:" in body
        assert "seed_context: ctx" in body
        assert "category_b_overrides:" in body
        assert "token_budget: '2048'" in body or "token_budget: \"2048\"" in body
