"""Every CRD property must reach the bundle manifests, not just the base CRDs.

The operator ships its CRDs twice:

* ``operator/config/crd/bases/*.yaml`` — generated by ``controller-gen``, applied
  directly by ``kubectl apply``.
* ``operator/bundle/manifests/*.yaml`` — what **OLM** installs.

Both are committed, and nothing keeps them in step. When a regeneration updates
the base and forgets the bundle, the failure is silent in the worst way: the API
server prunes unknown fields under structural-schema validation, so a CR setting
the missing field loses it before any reconciler runs. No error, no event, no log
line — the CR simply reads back without the value and the feature does nothing.

This has now happened twice:

* ``f431cae`` — AccCatalog / AccPackageInstall CRDs missing from the bundle
  entirely, which surfaced as a CrashLoopBackOff.
* ``85bdfbb`` (2026-07-04) — regenerated the agentcorpora base CRD (+119 lines)
  and did not mirror it, leaving the bundle **12 properties behind** for six
  weeks. Among the casualties was the whole OpenShell ``spec.sandbox`` block
  including ``gatewayURL``, the switch that turns on Model 2 enforcement: on an
  OLM install it was pruned, so the sandbox stayed off while the CR read as
  though it were configured.

The repository has no CI, so this test is the only thing standing between that
and a third occurrence. It runs in the ordinary suite and needs no cluster.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
BASES = REPO / "operator" / "config" / "crd" / "bases"
BUNDLE = REPO / "operator" / "bundle" / "manifests"

# Property keys sit at >= 6 spaces of indent and are bare `name:` lines. This is
# deliberately textual rather than a YAML walk: it is insensitive to how deeply
# a property is nested, which is exactly the property we care about here.
_PROP = re.compile(r"^\s{6,}([a-zA-Z][a-zA-Z0-9]*):\s*$", re.M)


def _properties(path: Path) -> set[str]:
    return set(_PROP.findall(path.read_text(encoding="utf-8")))


def _crd_pairs() -> list[tuple[Path, Path]]:
    if not BASES.is_dir():
        return []
    return [(b, BUNDLE / b.name) for b in sorted(BASES.glob("*.yaml"))]


pytestmark = pytest.mark.skipif(
    not BASES.is_dir(), reason="operator CRDs not present in this checkout"
)


@pytest.mark.parametrize(
    "base", [p[0] for p in _crd_pairs()], ids=lambda p: p.name
)
def test_crd_is_shipped_in_the_bundle(base: Path) -> None:
    """A CRD that exists as a base but not in the bundle is not installed by OLM."""
    assert (BUNDLE / base.name).is_file(), (
        f"{base.name} has no counterpart in operator/bundle/manifests/. An OLM "
        f"install would not create this CRD at all — the failure mode behind "
        f"f431cae (CrashLoopBackOff)."
    )


@pytest.mark.parametrize(
    "base,bundled", _crd_pairs(), ids=lambda p: p.name if isinstance(p, Path) else ""
)
def test_bundle_carries_every_base_property(base: Path, bundled: Path) -> None:
    """The bundle must be a superset of the base CRD's properties.

    Superset rather than equality on purpose: the bundle may legitimately gain
    OLM-specific additions. What it must never do is *lack* something the base
    declares, because that is what the API server prunes.
    """
    if not bundled.is_file():
        pytest.skip("covered by test_crd_is_shipped_in_the_bundle")

    missing = sorted(_properties(base) - _properties(bundled))
    assert not missing, (
        f"{bundled.name} is {len(missing)} propert"
        f"{'y' if len(missing) == 1 else 'ies'} behind {base.name}: "
        f"{', '.join(missing)}.\n"
        f"OLM installs this manifest, so the API server will silently prune "
        f"these fields from any CR that sets them — no error is raised.\n"
        f"Fix: regenerate (`cd operator && make manifests`), restore the "
        f"hand-maintained config/rbac/role.yaml, then mirror the regenerated "
        f"CRD into operator/bundle/manifests/."
    )
