//go:build !ignore_autogenerated

// Copyright 2026 ACC Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// DeepCopy functions for Stage 1.6 CRDs (AccPackageInstall, AccCatalog).
// Hand-written matching controller-gen's emission style; replace with
// generator output on the next `make generate` run.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// --------------------------------------------------------------------
// AccPackageInstall
// --------------------------------------------------------------------

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccPackageInstall) DeepCopyInto(out *AccPackageInstall) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccPackageInstall.
func (in *AccPackageInstall) DeepCopy() *AccPackageInstall {
	if in == nil {
		return nil
	}
	out := new(AccPackageInstall)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccPackageInstall) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccPackageInstallList) DeepCopyInto(out *AccPackageInstallList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AccPackageInstall, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccPackageInstallList.
func (in *AccPackageInstallList) DeepCopy() *AccPackageInstallList {
	if in == nil {
		return nil
	}
	out := new(AccPackageInstallList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccPackageInstallList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccPackageInstallSpec) DeepCopyInto(out *AccPackageInstallSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccPackageInstallSpec.
func (in *AccPackageInstallSpec) DeepCopy() *AccPackageInstallSpec {
	if in == nil {
		return nil
	}
	out := new(AccPackageInstallSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccPackageInstallStatus) DeepCopyInto(out *AccPackageInstallStatus) {
	*out = *in
	if in.LastInstalledAt != nil {
		in, out := &in.LastInstalledAt, &out.LastInstalledAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccPackageInstallStatus.
func (in *AccPackageInstallStatus) DeepCopy() *AccPackageInstallStatus {
	if in == nil {
		return nil
	}
	out := new(AccPackageInstallStatus)
	in.DeepCopyInto(out)
	return out
}

// --------------------------------------------------------------------
// AccCatalog
// --------------------------------------------------------------------

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccCatalog) DeepCopyInto(out *AccCatalog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccCatalog.
func (in *AccCatalog) DeepCopy() *AccCatalog {
	if in == nil {
		return nil
	}
	out := new(AccCatalog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccCatalog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccCatalogList) DeepCopyInto(out *AccCatalogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AccCatalog, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccCatalogList.
func (in *AccCatalogList) DeepCopy() *AccCatalogList {
	if in == nil {
		return nil
	}
	out := new(AccCatalogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccCatalogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccCatalogSpec) DeepCopyInto(out *AccCatalogSpec) {
	*out = *in
	out.RequiredSigner = in.RequiredSigner
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccCatalogSpec.
func (in *AccCatalogSpec) DeepCopy() *AccCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(AccCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccCatalogStatus) DeepCopyInto(out *AccCatalogStatus) {
	*out = *in
	if in.LastRenderedAt != nil {
		in, out := &in.LastRenderedAt, &out.LastRenderedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccCatalogStatus.
func (in *AccCatalogStatus) DeepCopy() *AccCatalogStatus {
	if in == nil {
		return nil
	}
	out := new(AccCatalogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogRequiredSigner) DeepCopyInto(out *CatalogRequiredSigner) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogRequiredSigner.
func (in *CatalogRequiredSigner) DeepCopy() *CatalogRequiredSigner {
	if in == nil {
		return nil
	}
	out := new(CatalogRequiredSigner)
	in.DeepCopyInto(out)
	return out
}
