//go:build !ignore_autogenerated

// Copyright 2026 ACC Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccCatalog) DeepCopyInto(out *AccCatalog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccCatalog.
func (in *AccCatalog) DeepCopy() *AccCatalog {
	if in == nil {
		return nil
	}
	out := new(AccCatalog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccCatalog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccCatalogList) DeepCopyInto(out *AccCatalogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccCatalog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccCatalogList.
func (in *AccCatalogList) DeepCopy() *AccCatalogList {
	if in == nil {
		return nil
	}
	out := new(AccCatalogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccCatalogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccCatalogSpec) DeepCopyInto(out *AccCatalogSpec) {
	*out = *in
	out.RequiredSigner = in.RequiredSigner
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccCatalogSpec.
func (in *AccCatalogSpec) DeepCopy() *AccCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(AccCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccCatalogStatus) DeepCopyInto(out *AccCatalogStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastRenderedAt != nil {
		in, out := &in.LastRenderedAt, &out.LastRenderedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccCatalogStatus.
func (in *AccCatalogStatus) DeepCopy() *AccCatalogStatus {
	if in == nil {
		return nil
	}
	out := new(AccCatalogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccPackageInstall) DeepCopyInto(out *AccPackageInstall) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccPackageInstall.
func (in *AccPackageInstall) DeepCopy() *AccPackageInstall {
	if in == nil {
		return nil
	}
	out := new(AccPackageInstall)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccPackageInstall) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccPackageInstallList) DeepCopyInto(out *AccPackageInstallList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccPackageInstall, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccPackageInstallList.
func (in *AccPackageInstallList) DeepCopy() *AccPackageInstallList {
	if in == nil {
		return nil
	}
	out := new(AccPackageInstallList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccPackageInstallList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccPackageInstallSpec) DeepCopyInto(out *AccPackageInstallSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccPackageInstallSpec.
func (in *AccPackageInstallSpec) DeepCopy() *AccPackageInstallSpec {
	if in == nil {
		return nil
	}
	out := new(AccPackageInstallSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccPackageInstallStatus) DeepCopyInto(out *AccPackageInstallStatus) {
	*out = *in
	if in.LastInstalledAt != nil {
		in, out := &in.LastInstalledAt, &out.LastInstalledAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccPackageInstallStatus.
func (in *AccPackageInstallStatus) DeepCopy() *AccPackageInstallStatus {
	if in == nil {
		return nil
	}
	out := new(AccPackageInstallStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCollective) DeepCopyInto(out *AgentCollective) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCollective.
func (in *AgentCollective) DeepCopy() *AgentCollective {
	if in == nil {
		return nil
	}
	out := new(AgentCollective)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentCollective) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCollectiveList) DeepCopyInto(out *AgentCollectiveList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentCollective, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCollectiveList.
func (in *AgentCollectiveList) DeepCopy() *AgentCollectiveList {
	if in == nil {
		return nil
	}
	out := new(AgentCollectiveList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentCollectiveList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCollectiveSpec) DeepCopyInto(out *AgentCollectiveSpec) {
	*out = *in
	out.CorpusRef = in.CorpusRef
	if in.Agents != nil {
		in, out := &in.Agents, &out.Agents
		*out = make([]AgentRoleSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LLM.DeepCopyInto(&out.LLM)
	if in.Scaling != nil {
		in, out := &in.Scaling, &out.Scaling
		*out = new(ScalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleDefinition != nil {
		in, out := &in.RoleDefinition, &out.RoleDefinition
		*out = new(RoleDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.Spiffe != nil {
		in, out := &in.Spiffe, &out.Spiffe
		*out = new(SpiffeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Kagenti != nil {
		in, out := &in.Kagenti, &out.Kagenti
		*out = new(KagentiSpec)
		**out = **in
	}
	if in.DisableAssistant != nil {
		in, out := &in.DisableAssistant, &out.DisableAssistant
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCollectiveSpec.
func (in *AgentCollectiveSpec) DeepCopy() *AgentCollectiveSpec {
	if in == nil {
		return nil
	}
	out := new(AgentCollectiveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCollectiveStatus) DeepCopyInto(out *AgentCollectiveStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReadyAgents != nil {
		in, out := &in.ReadyAgents, &out.ReadyAgents
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DesiredAgents != nil {
		in, out := &in.DesiredAgents, &out.DesiredAgents
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCollectiveStatus.
func (in *AgentCollectiveStatus) DeepCopy() *AgentCollectiveStatus {
	if in == nil {
		return nil
	}
	out := new(AgentCollectiveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCorpus) DeepCopyInto(out *AgentCorpus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCorpus.
func (in *AgentCorpus) DeepCopy() *AgentCorpus {
	if in == nil {
		return nil
	}
	out := new(AgentCorpus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentCorpus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCorpusList) DeepCopyInto(out *AgentCorpusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentCorpus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCorpusList.
func (in *AgentCorpusList) DeepCopy() *AgentCorpusList {
	if in == nil {
		return nil
	}
	out := new(AgentCorpusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentCorpusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCorpusSpec) DeepCopyInto(out *AgentCorpusSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Collectives != nil {
		in, out := &in.Collectives, &out.Collectives
		*out = make([]CollectiveRef, len(*in))
		copy(*out, *in)
	}
	in.Infrastructure.DeepCopyInto(&out.Infrastructure)
	in.Governance.DeepCopyInto(&out.Governance)
	if in.Kafka != nil {
		in, out := &in.Kafka, &out.Kafka
		*out = new(KafkaSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Observability.DeepCopyInto(&out.Observability)
	out.UpgradePolicy = in.UpgradePolicy
	if in.Edge != nil {
		in, out := &in.Edge, &out.Edge
		*out = new(EdgeSpec)
		**out = **in
	}
	if in.RHOAI != nil {
		in, out := &in.RHOAI, &out.RHOAI
		*out = new(RHOAISpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TUI != nil {
		in, out := &in.TUI, &out.TUI
		*out = new(TUISpec)
		(*in).DeepCopyInto(*out)
	}
	if in.WebGUI != nil {
		in, out := &in.WebGUI, &out.WebGUI
		*out = new(WebGUISpec)
		(*in).DeepCopyInto(*out)
	}
	if in.BootstrapDefaultCatalog != nil {
		in, out := &in.BootstrapDefaultCatalog, &out.BootstrapDefaultCatalog
		*out = new(bool)
		**out = **in
	}
	if in.NetworkPolicy != nil {
		in, out := &in.NetworkPolicy, &out.NetworkPolicy
		*out = new(NetworkPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MCPServers != nil {
		in, out := &in.MCPServers, &out.MCPServers
		*out = make([]MCPServerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCorpusSpec.
func (in *AgentCorpusSpec) DeepCopy() *AgentCorpusSpec {
	if in == nil {
		return nil
	}
	out := new(AgentCorpusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCorpusStatus) DeepCopyInto(out *AgentCorpusStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Prerequisites = in.Prerequisites
	out.Infrastructure = in.Infrastructure
	if in.CollectiveStatuses != nil {
		in, out := &in.CollectiveStatuses, &out.CollectiveStatuses
		*out = make(map[string]CollectiveStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.MCPServerStatuses != nil {
		in, out := &in.MCPServerStatuses, &out.MCPServerStatuses
		*out = make(map[string]MCPServerStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.NetworkPolicy = in.NetworkPolicy
	out.RuntimeEvidence = in.RuntimeEvidence
	if in.AvailableRHOAIModels != nil {
		in, out := &in.AvailableRHOAIModels, &out.AvailableRHOAIModels
		*out = make([]RHOAIModelRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCorpusStatus.
func (in *AgentCorpusStatus) DeepCopy() *AgentCorpusStatus {
	if in == nil {
		return nil
	}
	out := new(AgentCorpusStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRoleSpec) DeepCopyInto(out *AgentRoleSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraEnv != nil {
		in, out := &in.ExtraEnv, &out.ExtraEnv
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeClaimTemplates != nil {
		in, out := &in.VolumeClaimTemplates, &out.VolumeClaimTemplates
		*out = make([]corev1.PersistentVolumeClaimTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRoleSpec.
func (in *AgentRoleSpec) DeepCopy() *AgentRoleSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnthropicSpec) DeepCopyInto(out *AnthropicSpec) {
	*out = *in
	in.APIKeySecretRef.DeepCopyInto(&out.APIKeySecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnthropicSpec.
func (in *AnthropicSpec) DeepCopy() *AnthropicSpec {
	if in == nil {
		return nil
	}
	out := new(AnthropicSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogRequiredSigner) DeepCopyInto(out *CatalogRequiredSigner) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogRequiredSigner.
func (in *CatalogRequiredSigner) DeepCopy() *CatalogRequiredSigner {
	if in == nil {
		return nil
	}
	out := new(CatalogRequiredSigner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CategoryASpec) DeepCopyInto(out *CategoryASpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CategoryASpec.
func (in *CategoryASpec) DeepCopy() *CategoryASpec {
	if in == nil {
		return nil
	}
	out := new(CategoryASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CategoryBSpec) DeepCopyInto(out *CategoryBSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CategoryBSpec.
func (in *CategoryBSpec) DeepCopy() *CategoryBSpec {
	if in == nil {
		return nil
	}
	out := new(CategoryBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CategoryCSpec) DeepCopyInto(out *CategoryCSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CategoryCSpec.
func (in *CategoryCSpec) DeepCopy() *CategoryCSpec {
	if in == nil {
		return nil
	}
	out := new(CategoryCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectiveRef) DeepCopyInto(out *CollectiveRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectiveRef.
func (in *CollectiveRef) DeepCopy() *CollectiveRef {
	if in == nil {
		return nil
	}
	out := new(CollectiveRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectiveStatus) DeepCopyInto(out *CollectiveStatus) {
	*out = *in
	if in.ReadyAgents != nil {
		in, out := &in.ReadyAgents, &out.ReadyAgents
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DesiredAgents != nil {
		in, out := &in.DesiredAgents, &out.DesiredAgents
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SharedModel != nil {
		in, out := &in.SharedModel, &out.SharedModel
		*out = new(SharedModelStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectiveStatus.
func (in *CollectiveStatus) DeepCopy() *CollectiveStatus {
	if in == nil {
		return nil
	}
	out := new(CollectiveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeSpec) DeepCopyInto(out *EdgeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeSpec.
func (in *EdgeSpec) DeepCopy() *EdgeSpec {
	if in == nil {
		return nil
	}
	out := new(EdgeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GovernanceSpec) DeepCopyInto(out *GovernanceSpec) {
	*out = *in
	out.CategoryA = in.CategoryA
	out.CategoryB = in.CategoryB
	if in.CategoryC != nil {
		in, out := &in.CategoryC, &out.CategoryC
		*out = new(CategoryCSpec)
		**out = **in
	}
	if in.RuntimeEvidence != nil {
		in, out := &in.RuntimeEvidence, &out.RuntimeEvidence
		*out = new(RuntimeEvidenceSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GovernanceSpec.
func (in *GovernanceSpec) DeepCopy() *GovernanceSpec {
	if in == nil {
		return nil
	}
	out := new(GovernanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureSpec) DeepCopyInto(out *InfrastructureSpec) {
	*out = *in
	in.NATS.DeepCopyInto(&out.NATS)
	in.Redis.DeepCopyInto(&out.Redis)
	if in.Milvus != nil {
		in, out := &in.Milvus, &out.Milvus
		*out = new(MilvusSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureSpec.
func (in *InfrastructureSpec) DeepCopy() *InfrastructureSpec {
	if in == nil {
		return nil
	}
	out := new(InfrastructureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureStatus) DeepCopyInto(out *InfrastructureStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureStatus.
func (in *InfrastructureStatus) DeepCopy() *InfrastructureStatus {
	if in == nil {
		return nil
	}
	out := new(InfrastructureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaSpec) DeepCopyInto(out *KafkaSpec) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(corev1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSpec.
func (in *KafkaSpec) DeepCopy() *KafkaSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KagentiSpec) DeepCopyInto(out *KagentiSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KagentiSpec.
func (in *KagentiSpec) DeepCopy() *KagentiSpec {
	if in == nil {
		return nil
	}
	out := new(KagentiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMSpec) DeepCopyInto(out *LLMSpec) {
	*out = *in
	if in.Ollama != nil {
		in, out := &in.Ollama, &out.Ollama
		*out = new(OllamaSpec)
		**out = **in
	}
	if in.Anthropic != nil {
		in, out := &in.Anthropic, &out.Anthropic
		*out = new(AnthropicSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.VLLM != nil {
		in, out := &in.VLLM, &out.VLLM
		*out = new(VLLMSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LlamaStack != nil {
		in, out := &in.LlamaStack, &out.LlamaStack
		*out = new(LlamaStackSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMSpec.
func (in *LLMSpec) DeepCopy() *LLMSpec {
	if in == nil {
		return nil
	}
	out := new(LLMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LlamaStackSpec) DeepCopyInto(out *LlamaStackSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LlamaStackSpec.
func (in *LlamaStackSpec) DeepCopy() *LlamaStackSpec {
	if in == nil {
		return nil
	}
	out := new(LlamaStackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerSpec) DeepCopyInto(out *MCPServerSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecretEnv != nil {
		in, out := &in.SecretEnv, &out.SecretEnv
		*out = make([]corev1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerSpec.
func (in *MCPServerSpec) DeepCopy() *MCPServerSpec {
	if in == nil {
		return nil
	}
	out := new(MCPServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerStatus) DeepCopyInto(out *MCPServerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerStatus.
func (in *MCPServerStatus) DeepCopy() *MCPServerStatus {
	if in == nil {
		return nil
	}
	out := new(MCPServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MilvusSpec) DeepCopyInto(out *MilvusSpec) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(corev1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MilvusSpec.
func (in *MilvusSpec) DeepCopy() *MilvusSpec {
	if in == nil {
		return nil
	}
	out := new(MilvusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NATSSpec) DeepCopyInto(out *NATSSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.NKeyAuth != nil {
		in, out := &in.NKeyAuth, &out.NKeyAuth
		*out = new(NKeyAuthSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NATSSpec.
func (in *NATSSpec) DeepCopy() *NATSSpec {
	if in == nil {
		return nil
	}
	out := new(NATSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NKeyAuthSpec) DeepCopyInto(out *NKeyAuthSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NKeyAuthSpec.
func (in *NKeyAuthSpec) DeepCopy() *NKeyAuthSpec {
	if in == nil {
		return nil
	}
	out := new(NKeyAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicySpec) DeepCopyInto(out *NetworkPolicySpec) {
	*out = *in
	if in.ExtraEgressFQDNs != nil {
		in, out := &in.ExtraEgressFQDNs, &out.ExtraEgressFQDNs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraEgressCIDRs != nil {
		in, out := &in.ExtraEgressCIDRs, &out.ExtraEgressCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedExternalLLM != nil {
		in, out := &in.AllowedExternalLLM, &out.AllowedExternalLLM
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicySpec.
func (in *NetworkPolicySpec) DeepCopy() *NetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicyStatus) DeepCopyInto(out *NetworkPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicyStatus.
func (in *NetworkPolicyStatus) DeepCopy() *NetworkPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OTelCollectorSpec) DeepCopyInto(out *OTelCollectorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OTelCollectorSpec.
func (in *OTelCollectorSpec) DeepCopy() *OTelCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(OTelCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilitySpec) DeepCopyInto(out *ObservabilitySpec) {
	*out = *in
	if in.OTelCollector != nil {
		in, out := &in.OTelCollector, &out.OTelCollector
		*out = new(OTelCollectorSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilitySpec.
func (in *ObservabilitySpec) DeepCopy() *ObservabilitySpec {
	if in == nil {
		return nil
	}
	out := new(ObservabilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OllamaSpec) DeepCopyInto(out *OllamaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OllamaSpec.
func (in *OllamaSpec) DeepCopy() *OllamaSpec {
	if in == nil {
		return nil
	}
	out := new(OllamaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrerequisiteStatus) DeepCopyInto(out *PrerequisiteStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrerequisiteStatus.
func (in *PrerequisiteStatus) DeepCopy() *PrerequisiteStatus {
	if in == nil {
		return nil
	}
	out := new(PrerequisiteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHOAIModelRef) DeepCopyInto(out *RHOAIModelRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHOAIModelRef.
func (in *RHOAIModelRef) DeepCopy() *RHOAIModelRef {
	if in == nil {
		return nil
	}
	out := new(RHOAIModelRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHOAISpec) DeepCopyInto(out *RHOAISpec) {
	*out = *in
	if in.RegisterNamespaceAsProject != nil {
		in, out := &in.RegisterNamespaceAsProject, &out.RegisterNamespaceAsProject
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHOAISpec.
func (in *RHOAISpec) DeepCopy() *RHOAISpec {
	if in == nil {
		return nil
	}
	out := new(RHOAISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisSpec) DeepCopyInto(out *RedisSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisSpec.
func (in *RedisSpec) DeepCopy() *RedisSpec {
	if in == nil {
		return nil
	}
	out := new(RedisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleDefinition) DeepCopyInto(out *RoleDefinition) {
	*out = *in
	if in.TaskTypes != nil {
		in, out := &in.TaskTypes, &out.TaskTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedActions != nil {
		in, out := &in.AllowedActions, &out.AllowedActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CategoryBOverrides != nil {
		in, out := &in.CategoryBOverrides, &out.CategoryBOverrides
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleDefinition.
func (in *RoleDefinition) DeepCopy() *RoleDefinition {
	if in == nil {
		return nil
	}
	out := new(RoleDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleScalingSpec) DeepCopyInto(out *RoleScalingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleScalingSpec.
func (in *RoleScalingSpec) DeepCopy() *RoleScalingSpec {
	if in == nil {
		return nil
	}
	out := new(RoleScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeEvidenceSpec) DeepCopyInto(out *RuntimeEvidenceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeEvidenceSpec.
func (in *RuntimeEvidenceSpec) DeepCopy() *RuntimeEvidenceSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeEvidenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeEvidenceStatus) DeepCopyInto(out *RuntimeEvidenceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeEvidenceStatus.
func (in *RuntimeEvidenceStatus) DeepCopy() *RuntimeEvidenceStatus {
	if in == nil {
		return nil
	}
	out := new(RuntimeEvidenceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingSpec) DeepCopyInto(out *ScalingSpec) {
	*out = *in
	if in.RoleScaling != nil {
		in, out := &in.RoleScaling, &out.RoleScaling
		*out = make([]RoleScalingSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingSpec.
func (in *ScalingSpec) DeepCopy() *ScalingSpec {
	if in == nil {
		return nil
	}
	out := new(ScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedModelStatus) DeepCopyInto(out *SharedModelStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedModelStatus.
func (in *SharedModelStatus) DeepCopy() *SharedModelStatus {
	if in == nil {
		return nil
	}
	out := new(SharedModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpiffeSpec) DeepCopyInto(out *SpiffeSpec) {
	*out = *in
	if in.FederationPeers != nil {
		in, out := &in.FederationPeers, &out.FederationPeers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpiffeSpec.
func (in *SpiffeSpec) DeepCopy() *SpiffeSpec {
	if in == nil {
		return nil
	}
	out := new(SpiffeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TUISpec) DeepCopyInto(out *TUISpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TUISpec.
func (in *TUISpec) DeepCopy() *TUISpec {
	if in == nil {
		return nil
	}
	out := new(TUISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradePolicySpec) DeepCopyInto(out *UpgradePolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradePolicySpec.
func (in *UpgradePolicySpec) DeepCopy() *UpgradePolicySpec {
	if in == nil {
		return nil
	}
	out := new(UpgradePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLLMSpec) DeepCopyInto(out *VLLMSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLLMSpec.
func (in *VLLMSpec) DeepCopy() *VLLMSpec {
	if in == nil {
		return nil
	}
	out := new(VLLMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebGUIKeycloakSpec) DeepCopyInto(out *WebGUIKeycloakSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebGUIKeycloakSpec.
func (in *WebGUIKeycloakSpec) DeepCopy() *WebGUIKeycloakSpec {
	if in == nil {
		return nil
	}
	out := new(WebGUIKeycloakSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebGUISpec) DeepCopyInto(out *WebGUISpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Keycloak != nil {
		in, out := &in.Keycloak, &out.Keycloak
		*out = new(WebGUIKeycloakSpec)
		**out = **in
	}
	if in.GroupMappings != nil {
		in, out := &in.GroupMappings, &out.GroupMappings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Route != nil {
		in, out := &in.Route, &out.Route
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebGUISpec.
func (in *WebGUISpec) DeepCopy() *WebGUISpec {
	if in == nil {
		return nil
	}
	out := new(WebGUISpec)
	in.DeepCopyInto(out)
	return out
}
