//go:build !ignore_autogenerated

// Copyright 2026 ACC Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another of the same type.
func (in *AgentCorpus) DeepCopyInto(out *AgentCorpus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of this AgentCorpus.
func (in *AgentCorpus) DeepCopy() *AgentCorpus {
	if in == nil {
		return nil
	}
	out := new(AgentCorpus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *AgentCorpus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of AgentCorpusList.
func (in *AgentCorpusList) DeepCopyInto(out *AgentCorpusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentCorpus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of AgentCorpusList.
func (in *AgentCorpusList) DeepCopy() *AgentCorpusList {
	if in == nil {
		return nil
	}
	out := new(AgentCorpusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *AgentCorpusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies AgentCorpusSpec.
func (in *AgentCorpusSpec) DeepCopyInto(out *AgentCorpusSpec) {
	*out = *in
	if in.Collectives != nil {
		in, out := &in.Collectives, &out.Collectives
		*out = make([]CollectiveRef, len(*in))
		copy(*out, *in)
	}
	in.Infrastructure.DeepCopyInto(&out.Infrastructure)
	in.Governance.DeepCopyInto(&out.Governance)
	if in.Kafka != nil {
		in, out := &in.Kafka, &out.Kafka
		*out = new(KafkaSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Observability.DeepCopyInto(&out.Observability)
	out.UpgradePolicy = in.UpgradePolicy
}

// DeepCopyInto copies InfrastructureSpec.
func (in *InfrastructureSpec) DeepCopyInto(out *InfrastructureSpec) {
	*out = *in
	in.NATS.DeepCopyInto(&out.NATS)
	in.Redis.DeepCopyInto(&out.Redis)
	if in.Milvus != nil {
		in, out := &in.Milvus, &out.Milvus
		*out = new(MilvusSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopyInto copies NATSSpec.
func (in *NATSSpec) DeepCopyInto(out *NATSSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopyInto copies RedisSpec.
func (in *RedisSpec) DeepCopyInto(out *RedisSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopyInto copies MilvusSpec.
func (in *MilvusSpec) DeepCopyInto(out *MilvusSpec) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(corev1.SecretReference)
		**out = **in
	}
}

// DeepCopyInto copies GovernanceSpec.
func (in *GovernanceSpec) DeepCopyInto(out *GovernanceSpec) {
	*out = *in
	out.CategoryA = in.CategoryA
	out.CategoryB = in.CategoryB
	if in.CategoryC != nil {
		in, out := &in.CategoryC, &out.CategoryC
		*out = new(CategoryCSpec)
		**out = **in
	}
}

// DeepCopyInto copies KafkaSpec.
func (in *KafkaSpec) DeepCopyInto(out *KafkaSpec) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(corev1.SecretReference)
		**out = **in
	}
}

// DeepCopyInto copies ObservabilitySpec.
func (in *ObservabilitySpec) DeepCopyInto(out *ObservabilitySpec) {
	*out = *in
	if in.OTelCollector != nil {
		in, out := &in.OTelCollector, &out.OTelCollector
		*out = new(OTelCollectorSpec)
		**out = **in
	}
}

// DeepCopyInto copies AgentCorpusStatus.
func (in *AgentCorpusStatus) DeepCopyInto(out *AgentCorpusStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Prerequisites = in.Prerequisites
	out.Infrastructure = in.Infrastructure
	if in.CollectiveStatuses != nil {
		in, out := &in.CollectiveStatuses, &out.CollectiveStatuses
		*out = make(map[string]CollectiveStatus, len(*in))
		for k, v := range *in {
			(*out)[k] = *v.DeepCopy()
		}
	}
}

// DeepCopy returns a deep copy of CollectiveStatus.
func (in *CollectiveStatus) DeepCopy() *CollectiveStatus {
	if in == nil {
		return nil
	}
	out := new(CollectiveStatus)
	*out = *in
	if in.ReadyAgents != nil {
		in, out := &in.ReadyAgents, &out.ReadyAgents
		*out = make(map[string]int32, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.DesiredAgents != nil {
		in, out := &in.DesiredAgents, &out.DesiredAgents
		*out = make(map[string]int32, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return out
}

// -----------------------------------------------------------------------
// AgentCollective
// -----------------------------------------------------------------------

// DeepCopyInto copies AgentCollective.
func (in *AgentCollective) DeepCopyInto(out *AgentCollective) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of AgentCollective.
func (in *AgentCollective) DeepCopy() *AgentCollective {
	if in == nil {
		return nil
	}
	out := new(AgentCollective)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *AgentCollective) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies AgentCollectiveList.
func (in *AgentCollectiveList) DeepCopyInto(out *AgentCollectiveList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentCollective, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of AgentCollectiveList.
func (in *AgentCollectiveList) DeepCopy() *AgentCollectiveList {
	if in == nil {
		return nil
	}
	out := new(AgentCollectiveList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *AgentCollectiveList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies AgentCollectiveSpec.
func (in *AgentCollectiveSpec) DeepCopyInto(out *AgentCollectiveSpec) {
	*out = *in
	out.CorpusRef = in.CorpusRef
	if in.Agents != nil {
		in, out := &in.Agents, &out.Agents
		*out = make([]AgentRoleSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LLM.DeepCopyInto(&out.LLM)
	if in.Scaling != nil {
		in, out := &in.Scaling, &out.Scaling
		*out = new(ScalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleDefinition != nil {
		in, out := &in.RoleDefinition, &out.RoleDefinition
		*out = new(RoleDefinition)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopyInto copies RoleDefinition.
func (in *RoleDefinition) DeepCopyInto(out *RoleDefinition) {
	*out = *in
	if in.TaskTypes != nil {
		in, out := &in.TaskTypes, &out.TaskTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedActions != nil {
		in, out := &in.AllowedActions, &out.AllowedActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CategoryBOverrides != nil {
		in, out := &in.CategoryBOverrides, &out.CategoryBOverrides
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy returns a deep copy of RoleDefinition.
func (in *RoleDefinition) DeepCopy() *RoleDefinition {
	if in == nil {
		return nil
	}
	out := new(RoleDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies AgentRoleSpec.
func (in *AgentRoleSpec) DeepCopyInto(out *AgentRoleSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraEnv != nil {
		in, out := &in.ExtraEnv, &out.ExtraEnv
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeClaimTemplates != nil {
		in, out := &in.VolumeClaimTemplates, &out.VolumeClaimTemplates
		*out = make([]corev1.PersistentVolumeClaimTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyInto copies LLMSpec.
func (in *LLMSpec) DeepCopyInto(out *LLMSpec) {
	*out = *in
	if in.Ollama != nil {
		in, out := &in.Ollama, &out.Ollama
		*out = new(OllamaSpec)
		**out = **in
	}
	if in.Anthropic != nil {
		in, out := &in.Anthropic, &out.Anthropic
		*out = new(AnthropicSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.VLLM != nil {
		in, out := &in.VLLM, &out.VLLM
		*out = new(VLLMSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LlamaStack != nil {
		in, out := &in.LlamaStack, &out.LlamaStack
		*out = new(LlamaStackSpec)
		**out = **in
	}
}

// DeepCopyInto copies AnthropicSpec.
func (in *AnthropicSpec) DeepCopyInto(out *AnthropicSpec) {
	*out = *in
	out.APIKeySecretRef = in.APIKeySecretRef
}

// DeepCopyInto copies VLLMSpec.
func (in *VLLMSpec) DeepCopyInto(out *VLLMSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopyInto copies ScalingSpec.
func (in *ScalingSpec) DeepCopyInto(out *ScalingSpec) {
	*out = *in
	if in.RoleScaling != nil {
		in, out := &in.RoleScaling, &out.RoleScaling
		*out = make([]RoleScalingSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto copies AgentCollectiveStatus.
func (in *AgentCollectiveStatus) DeepCopyInto(out *AgentCollectiveStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReadyAgents != nil {
		in, out := &in.ReadyAgents, &out.ReadyAgents
		*out = make(map[string]int32, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.DesiredAgents != nil {
		in, out := &in.DesiredAgents, &out.DesiredAgents
		*out = make(map[string]int32, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
}
