// Copyright 2026 ACC Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

package collective

import (
	corev1 "k8s.io/api/core/v1"

	accv1alpha1 "github.com/redhat-ai-dev/agentic-cell-corpus/operator/api/v1alpha1"
)

// SPIFFE sidecar wiring (proposal 011 PR-3).
//
// When an AgentCollective has spec.spiffe.enabled=true, every agent
// pod gains a `spiffe-helper` sidecar.  spiffe-helper talks to the
// SPIRE Agent's Workload API (mounted via the SPIFFE CSI Driver) and
// continuously writes the pod's X.509-SVID + JWT-SVID into a shared
// emptyDir.  The agent container reads the SVID files from that
// emptyDir — no agent code change beyond the env vars set here.
//
// The agent-side consumption (verifying ROLE_UPDATE JWT-SVIDs,
// loading the X.509-SVID for NATS mTLS) lands in proposal 011 PR-4.
// PR-3 only provisions the files.
const (
	// spiffeSVIDDir is the in-pod path of the emptyDir that
	// spiffe-helper writes SVIDs into and the agent reads from.
	// Matches acc/config.py SpiffeConfig.svid_mount_path's default.
	spiffeSVIDDir = "/run/spire/sockets"

	// spiffeWorkloadAPIDir is where the SPIFFE CSI Driver mounts the
	// SPIRE Agent Workload API socket for the spiffe-helper sidecar.
	spiffeWorkloadAPIDir = "/spiffe-workload-api"

	// spiffeHelperConfigDir is where the rendered helper.conf
	// ConfigMap is mounted into the spiffe-helper sidecar.
	spiffeHelperConfigDir = "/etc/spiffe-helper"

	// spiffeHelperImage is the pinned spiffe-helper image.  Upstream
	// SPIFFE project image; bump deliberately.
	spiffeHelperImage = "ghcr.io/spiffe/spiffe-helper:0.9.0"

	// SVID file names spiffe-helper writes.  The agent reads these
	// paths via the ACC_SVID_* env vars.
	spiffeX509File = "svid.pem"
	spiffeJWTFile  = "jwt_svid.token"
	// spiffeJWTBundleFile is the JWKS the agent verifies JWT-SVIDs
	// against (proposal 011 PR-4).  Must match
	// acc.spiffe_verify.DEFAULT_JWT_BUNDLE_FILE.
	spiffeJWTBundleFile = "jwt_bundle.json"

	// jwtAudience is the audience claim required on ROLE_UPDATE
	// JWT-SVIDs.  Matches acc/config.py SpiffeConfig.jwt_audience's
	// default; PR-4's verifier checks for it.
	jwtAudience = "acc-role-update"

	// spirePodAnnotation tells spire-controller-manager's webhook to
	// attest this pod.
	spirePodAnnotationKey   = "spiffe.io/spire-managed-identity"
	spirePodAnnotationValue = "true"

	// Volume names.
	spiffeSVIDVolume        = "spiffe-svids"
	spiffeWorkloadAPIVolume = "spiffe-workload-api"
	spiffeHelperCfgVolume   = "spiffe-helper-config"

	// spiffeHelperConfigMapSuffix is appended to the collective name
	// to form the per-collective helper.conf ConfigMap name.
	spiffeHelperConfigMapSuffix = "-spiffe-helper"

	// spiffeHelperConfigKey is the ConfigMap key holding helper.conf.
	spiffeHelperConfigKey = "helper.conf"
)

// SpiffeEnabled reports whether the collective opted into SPIFFE.
// Centralised so the sidecar wiring + the SpiffeReconciler agree.
func SpiffeEnabled(collective *accv1alpha1.AgentCollective) bool {
	return collective.Spec.Spiffe != nil && collective.Spec.Spiffe.Enabled
}

// SpiffeHelperConfigMapName returns the per-collective helper.conf
// ConfigMap name.
func SpiffeHelperConfigMapName(collective *accv1alpha1.AgentCollective) string {
	return collective.Name + spiffeHelperConfigMapSuffix
}

// RenderSpiffeHelperConfig returns the HCL `helper.conf` that drives
// the spiffe-helper sidecar.  It is deterministic — the same for every
// SPIFFE-enabled collective today — but kept as a function so PR-4 /
// 012 can parameterise it (e.g. per-collective JWT audiences).
func RenderSpiffeHelperConfig() string {
	return `# Generated by the ACC operator (proposal 011 PR-3).
# Drives the spiffe-helper sidecar that materialises this pod's
# X.509-SVID and JWT-SVID into ` + spiffeSVIDDir + `.
agent_address = "` + spiffeWorkloadAPIDir + `/spire-agent.sock"
cert_dir = "` + spiffeSVIDDir + `"
svid_file_name = "` + spiffeX509File + `"
svid_key_file_name = "svid_key.pem"
svid_bundle_file_name = "svid_bundle.pem"
jwt_svids = [
  {
    jwt_audience = "` + jwtAudience + `"
    jwt_svid_file_name = "` + spiffeJWTFile + `"
  }
]
# JWT trust bundle (JWKS) — the agent's acc.spiffe_verify reads this
# to verify ROLE_UPDATE JWT-SVIDs (proposal 011 PR-4).
jwt_bundle_file_name = "` + spiffeJWTBundleFile + `"
`
}

// ApplySpiffeSidecar mutates a freshly-built agent Deployment in place
// to add the spiffe-helper sidecar + supporting volumes/mounts/env,
// when the collective has SPIFFE enabled.  No-op otherwise.
//
// helperConfigMapName is the name of the ConfigMap carrying the
// rendered helper.conf (created by AgentDeploymentReconciler before
// this is called).
// tmpl is the agent pod template (&workload.Spec.Template); proposal 024
// switched agents from Deployment to StatefulSet, so this takes the pod
// template directly to stay workload-kind agnostic.
func ApplySpiffeSidecar(
	tmpl *corev1.PodTemplateSpec,
	collective *accv1alpha1.AgentCollective,
	helperConfigMapName string,
) {
	if !SpiffeEnabled(collective) {
		return
	}

	podSpec := &tmpl.Spec

	// 1. Pod annotation — spire-controller-manager's webhook keys on it.
	if tmpl.ObjectMeta.Annotations == nil {
		tmpl.ObjectMeta.Annotations = map[string]string{}
	}
	tmpl.ObjectMeta.Annotations[spirePodAnnotationKey] = spirePodAnnotationValue

	// 2. Volumes: the shared SVID emptyDir, the CSI Workload-API
	//    volume, and the helper.conf ConfigMap.
	podSpec.Volumes = append(podSpec.Volumes,
		corev1.Volume{
			Name: spiffeSVIDVolume,
			VolumeSource: corev1.VolumeSource{
				EmptyDir: &corev1.EmptyDirVolumeSource{},
			},
		},
		corev1.Volume{
			Name: spiffeWorkloadAPIVolume,
			VolumeSource: corev1.VolumeSource{
				CSI: &corev1.CSIVolumeSource{
					Driver:   "csi.spiffe.io",
					ReadOnly: ptrBool(true),
				},
			},
		},
		corev1.Volume{
			Name: spiffeHelperCfgVolume,
			VolumeSource: corev1.VolumeSource{
				ConfigMap: &corev1.ConfigMapVolumeSource{
					LocalObjectReference: corev1.LocalObjectReference{
						Name: helperConfigMapName,
					},
				},
			},
		},
	)

	// 3. The spiffe-helper sidecar container.
	podSpec.Containers = append(podSpec.Containers, corev1.Container{
		Name:  "spiffe-helper",
		Image: spiffeHelperImage,
		Args:  []string{"-config", spiffeHelperConfigDir + "/" + spiffeHelperConfigKey},
		VolumeMounts: []corev1.VolumeMount{
			{Name: spiffeSVIDVolume, MountPath: spiffeSVIDDir},
			{Name: spiffeWorkloadAPIVolume, MountPath: spiffeWorkloadAPIDir, ReadOnly: true},
			{Name: spiffeHelperCfgVolume, MountPath: spiffeHelperConfigDir, ReadOnly: true},
		},
	})

	// 4. Agent container (index 0) gets a read mount of the SVID dir
	//    plus the ACC_SVID_* env vars so its config picks them up.
	if len(podSpec.Containers) > 0 {
		agent := &podSpec.Containers[0]
		agent.VolumeMounts = append(agent.VolumeMounts, corev1.VolumeMount{
			Name:      spiffeSVIDVolume,
			MountPath: spiffeSVIDDir,
			ReadOnly:  true,
		})
		agent.Env = append(agent.Env,
			corev1.EnvVar{Name: "ACC_SPIFFE_SVID_MOUNT_PATH", Value: spiffeSVIDDir},
			corev1.EnvVar{Name: "ACC_SVID_X509_PATH", Value: spiffeSVIDDir + "/" + spiffeX509File},
			corev1.EnvVar{Name: "ACC_SVID_JWT_PATH", Value: spiffeSVIDDir + "/" + spiffeJWTFile},
		)
	}
}

// ptrBool is a tiny local helper — k8s.io/utils/ptr is already a dep
// but a one-liner keeps the import surface of this file minimal.
func ptrBool(b bool) *bool { return &b }
