"""Cluster identity + registry for multi-agent sub-clusters.

A *cluster* is a group of sub-agents instantiated together to solve one
PLAN step that the role's :class:`Estimator` (PR-2) decided is worth
parallelising.  Every signal emitted *by* a cluster member carries the
shared ``cluster_id`` so the TUI and the arbiter can fan-in events,
render topology, and cancel collectively.

This PR (PR-1) lays the *foundation only*:

* :class:`ClusterPlan` — the dataclass the estimator returns.
* :func:`register_cluster` / :func:`lookup_cluster` —
  in-memory + (optional) Redis-backed registry so independent
  processes (arbiter, TUI, sub-agents) agree on cluster identity.
* No estimation logic, no spawn fan-out, no TUI rendering — those
  arrive in PR-2 and PR-4 respectively.

Design intentions worth preserving across follow-up PRs:

* ``cluster_id`` is **always optional** on the wire.  A payload without
  it represents a single-agent task — the legacy behaviour every
  non-cluster-aware caller already produces.  No existing publisher
  needs to change to keep working.
* The registry is the *only* canonical lookup path.  Sub-agents must
  not infer cluster membership from message-routing side effects —
  membership is declared explicitly at register time so audit + cancel
  are deterministic.
* Redis is best-effort, not authoritative.  When Redis is unreachable
  (edge / disconnected) the in-memory registry still works for the
  current process.  This matches ACC's offline-first edge guarantee.
"""

from __future__ import annotations

import asyncio
import logging
import threading
import time
import uuid
from dataclasses import asdict, dataclass, field
from typing import Any

from acc.redis_compat import call_redis

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Public dataclass
# ---------------------------------------------------------------------------


@dataclass
class ClusterPlan:
    """One cluster's full description, returned by the estimator.

    Field semantics:

    * ``cluster_id`` — UUID4 hex, never re-used.  Generated by
      :func:`new_cluster_id` if the caller doesn't pass one.
    * ``target_role`` — every member is instantiated with this role.
      Mixed-role clusters are deferred to a follow-up; PR-2's estimator
      returns a single role per cluster on purpose (one decision,
      one cluster).
    * ``subagent_count`` — exact number of TASK_ASSIGN payloads the
      arbiter will publish.  Always ≥ 1.
    * ``skill_mix`` — flat list of skill names; the arbiter slices it
      across members (PR-2 implements the slicer).  Empty list = each
      sub-agent uses its role's ``default_skills``.
    * ``parent_task_id`` — the PLAN-step task_id that triggered the
      spawn.  Lets the TUI nest cluster topology under its originating
      task in Performance / prompt views.
    * ``estimated_difficulty`` — float in [0, 1] from the estimator;
      used purely as a UI signal today (rendered as a colour tint in
      PR-4) but kept on the wire so future analytics can train a
      better estimator from outcomes.
    * ``reason`` — short human-readable string from the estimator
      explaining the count + difficulty (e.g. ``"4200 tokens, +1
      security keyword"``).  Surfaced verbatim in the cluster panel.
    * ``created_at`` — wall-clock seconds; used for the 30 s grace
      window before a finished cluster falls out of the TUI panel
      (PR-4).
    """

    cluster_id: str
    target_role: str
    subagent_count: int
    parent_task_id: str
    skill_mix: list[str] = field(default_factory=list)
    estimated_difficulty: float = 0.0
    reason: str = ""
    created_at: float = field(default_factory=time.time)

    def __post_init__(self) -> None:
        if self.subagent_count < 1:
            raise ValueError(
                f"ClusterPlan.subagent_count must be >= 1, got "
                f"{self.subagent_count!r}"
            )
        if not (0.0 <= self.estimated_difficulty <= 1.0):
            raise ValueError(
                "ClusterPlan.estimated_difficulty must be in [0, 1], got "
                f"{self.estimated_difficulty!r}"
            )

    # Convenient (de)serialisation for Redis / NATS bodies.
    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> "ClusterPlan":
        # Defensive read — payloads from older publishers may be
        # missing newly-added fields.  Fill with safe defaults instead
        # of raising so the registry survives version skew.
        return cls(
            cluster_id=str(payload["cluster_id"]),
            target_role=str(payload.get("target_role", "")),
            subagent_count=int(payload.get("subagent_count", 1) or 1),
            parent_task_id=str(payload.get("parent_task_id", "")),
            skill_mix=list(payload.get("skill_mix", []) or []),
            estimated_difficulty=float(payload.get("estimated_difficulty", 0.0) or 0.0),
            reason=str(payload.get("reason", "") or ""),
            created_at=float(payload.get("created_at", time.time()) or time.time()),
        )


def new_cluster_id() -> str:
    """Generate a cluster_id distinct from task_id / agent_id space.

    Prefix ``c-`` makes log lines self-describing without an extra
    schema lookup — anyone reading ``cluster_id=c-deadbeef…`` knows
    exactly what they're looking at.  The 32-char hex tail keeps
    collision probability negligible for the lifetime of any operator
    deployment.
    """
    return f"c-{uuid.uuid4().hex}"


# ---------------------------------------------------------------------------
# Registry — in-memory authoritative + optional Redis mirror
# ---------------------------------------------------------------------------


# Module-global because the arbiter's reconciler thread, the task
# loop, and the cancel handler all need the same view; passing a
# registry instance through every signature would balloon call sites
# without buying isolation we'd ever exercise.
_REGISTRY: dict[str, ClusterPlan] = {}
_REGISTRY_LOCK = threading.Lock()

# Optional Redis client + key prefix.  ``configure_redis_mirror`` wires
# them in; until then the registry is purely in-memory and
# ``call_redis`` is never invoked.  This indirection lets edge nodes
# operate without a Redis dependency at all.
_REDIS_CLIENT: Any | None = None
_REDIS_KEY_PREFIX: str = "acc:cluster:"
_REDIS_TTL_S: int = 24 * 3600  # one-day grace; clusters are ephemeral


def configure_redis_mirror(
    client: Any | None,
    *,
    key_prefix: str = "acc:cluster:",
    ttl_s: int = 24 * 3600,
) -> None:
    """Wire the registry to a Redis client (sync or async — :mod:`redis_compat`
    detects the shape).  Pass ``client=None`` to detach.

    Idempotent — safe to call repeatedly during process startup.
    """
    global _REDIS_CLIENT, _REDIS_KEY_PREFIX, _REDIS_TTL_S
    _REDIS_CLIENT = client
    _REDIS_KEY_PREFIX = key_prefix
    _REDIS_TTL_S = int(ttl_s)


def register_cluster(plan: ClusterPlan) -> None:
    """Insert *plan* into the in-memory registry.

    Synchronous on purpose — every registry caller is on a hot dispatch
    path where awaiting Redis would serialise sub-agent fan-out.  The
    Redis mirror runs as a fire-and-forget background task scheduled
    from the running loop; failure to mirror is logged but never
    raised.  Local processes always see their own writes immediately.
    """
    with _REGISTRY_LOCK:
        _REGISTRY[plan.cluster_id] = plan

    if _REDIS_CLIENT is not None:
        # Schedule async mirror without blocking.  ``get_event_loop``
        # in 3.12+ raises if there is no running loop — fall back to
        # creating a new one only when called from a sync test path
        # (we still want the registry update to land).
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = None
        if loop is not None:
            loop.create_task(_mirror_to_redis(plan))


def lookup_cluster(cluster_id: str) -> ClusterPlan | None:
    """Return the registered plan or ``None``.

    Local memory wins by design — see :func:`register_cluster` for the
    rationale.  When the local process didn't witness the registration
    (e.g. TUI started after the arbiter spawned the cluster) callers
    should fall back to :func:`fetch_cluster_async` for a Redis read.
    """
    with _REGISTRY_LOCK:
        return _REGISTRY.get(cluster_id)


async def fetch_cluster_async(cluster_id: str) -> ClusterPlan | None:
    """Async lookup that consults Redis when the local cache misses.

    Used by the TUI cluster panel (PR-4) on first paint to backfill
    clusters that were spawned before the panel mounted.
    """
    cached = lookup_cluster(cluster_id)
    if cached is not None:
        return cached
    if _REDIS_CLIENT is None:
        return None

    key = _REDIS_KEY_PREFIX + cluster_id
    try:
        raw = await call_redis(_REDIS_CLIENT.get, key)
    except Exception:
        logger.exception("cluster: Redis lookup failed for %s", cluster_id)
        return None
    if not raw:
        return None
    try:
        import json as _json
        payload = _json.loads(
            raw.decode("utf-8") if isinstance(raw, (bytes, bytearray)) else raw
        )
    except (ValueError, AttributeError):
        logger.warning("cluster: corrupt Redis payload for %s", cluster_id)
        return None
    plan = ClusterPlan.from_dict(payload)
    # Populate local cache so subsequent sync lookups hit memory.
    with _REGISTRY_LOCK:
        _REGISTRY.setdefault(cluster_id, plan)
    return plan


def unregister_cluster(cluster_id: str) -> None:
    """Drop *cluster_id* from the local registry.

    Mirror to Redis is fire-and-forget.  Callers should invoke this
    when every cluster member has emitted TASK_COMPLETE and the 30 s
    UI grace window has elapsed (the arbiter owns the policy).
    """
    with _REGISTRY_LOCK:
        _REGISTRY.pop(cluster_id, None)
    if _REDIS_CLIENT is not None:
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = None
        if loop is not None:
            loop.create_task(_evict_from_redis(cluster_id))


def list_clusters() -> list[ClusterPlan]:
    """Snapshot of currently-registered clusters (for tests + TUI startup)."""
    with _REGISTRY_LOCK:
        return list(_REGISTRY.values())


# ---------------------------------------------------------------------------
# Redis mirror — never raises into caller paths
# ---------------------------------------------------------------------------


async def _mirror_to_redis(plan: ClusterPlan) -> None:
    if _REDIS_CLIENT is None:
        return
    key = _REDIS_KEY_PREFIX + plan.cluster_id
    try:
        import json as _json
        await call_redis(
            _REDIS_CLIENT.set,
            key,
            _json.dumps(plan.to_dict()),
            ex=_REDIS_TTL_S,
        )
    except Exception:
        logger.exception("cluster: Redis mirror failed for %s", plan.cluster_id)


async def _evict_from_redis(cluster_id: str) -> None:
    if _REDIS_CLIENT is None:
        return
    key = _REDIS_KEY_PREFIX + cluster_id
    try:
        await call_redis(_REDIS_CLIENT.delete, key)
    except Exception:
        logger.exception("cluster: Redis evict failed for %s", cluster_id)


# ---------------------------------------------------------------------------
# Test/reset hook
# ---------------------------------------------------------------------------


def _reset_for_tests() -> None:
    """Clear the in-memory registry + detach Redis mirror.

    Tests use this in fixture teardown so no cluster state leaks across
    test functions.  Production code MUST NOT call it.
    """
    global _REDIS_CLIENT
    with _REGISTRY_LOCK:
        _REGISTRY.clear()
    _REDIS_CLIENT = None
