"""ACC RoleCRDProjector — CRD → file projection (proposal 010 PR-3).

The mirror image of ``operator/internal/filewatch/`` on the Python side.
When ``role_sync.role_source`` is ``crd`` or ``mirror``, this module
polls the Kubernetes API for ``AgentCollective`` resources and writes
their ``spec.roleDefinition`` block to ``roles/<id>/role.yaml`` on the
agent's local filesystem.  The existing
:class:`acc.role_loader.RoleLoader` file-watcher then picks up the
write and triggers role hot-reload as usual — no separate code path
inside the agent's hot loop.

Design choices
--------------

* **Optional ``kubernetes`` dependency.**  We never hard-import the
  ``kubernetes`` library at module level — it's a heavy dep with
  many transitives, and agents running in ``role_source: files`` mode
  (the standalone default) should not need it.  The first call to
  :meth:`RoleCRDProjector.start` lazy-imports ``kubernetes``; if the
  import fails the projector logs a clear error and disables itself.
  Existing file-side behaviour is unaffected.

* **Protocol-based client.**  :class:`CRDClient` is a Protocol so unit
  tests can supply a fake without spinning up envtest or a kind
  cluster.  :class:`KubernetesCRDClient` is the production impl that
  wraps ``kubernetes.client.CustomObjectsApi``.

* **Polling, not watch.**  The Kubernetes ``watch`` API would be more
  efficient but harder to test deterministically.  Polling at
  ``poll_interval_s`` (default 30) matches the file-side watcher's
  cadence and keeps both directions symmetric.

* **Idempotent writes.**  ``project_one()`` reads the existing file
  (if any), compares canonicalised YAML, and only writes when the
  CRD content actually differs.  Prevents reconcile-loop oscillation
  in ``mirror`` mode (PR-4) and avoids spurious mtime bumps.

* **Sentinel comment.**  Generated files carry a header pointing
  back at the source CRD so an operator who ``cat``\\ s the file
  understands why it's there.

Proposal reference
------------------
``010 - Bi-directional file-CRD sync for role definitions.md``,
§5 step 3.
"""

from __future__ import annotations

import asyncio
import logging
import os
from pathlib import Path
from typing import Any, Optional, Protocol

import yaml

logger = logging.getLogger("acc.role_crd_loader")


# Sentinel comment prepended to every CRD-derived role.yaml file.
# The operator-side file watcher's parser ignores comments, so this is
# safe to round-trip through a mirror-mode reconcile.
_SENTINEL_HEADER = """\
# Generated by acc.role_crd_loader from CRD
# AgentCollective: {namespace}/{name}
# Source-of-truth: CRD (role_sync.role_source=crd or mirror).
# Do not edit this file by hand — set role_source=files in
# acc-config.yaml to make local files SOT instead.
# Last projected: {ts}
"""


def _utcnow_iso() -> str:
    """Tiny indirection so tests can monkeypatch the timestamp."""
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


class CRDClient(Protocol):
    """Minimal Kubernetes-CRD reader the projector depends on.

    Implementations must list all ``AgentCollective`` custom resources
    in a given namespace and return enough information to:

    1. Identify the role on disk (``name`` → ``roles/<name>/role.yaml``).
    2. Render the ``role_definition`` block (``spec.roleDefinition``
       as a plain ``dict``, snake_case-translated).

    Production: :class:`KubernetesCRDClient`.  Tests: any object with
    the same shape.
    """

    def list_collectives(self, namespace: str) -> list[dict[str, Any]]:
        """Return ``[{"name": str, "role_definition": dict | None}, ...]``.

        ``role_definition`` is ``None`` when the CR omits ``spec.roleDefinition``;
        in that case the projector skips the role rather than emitting an
        empty file.

        Implementations should translate camelCase CRD field names
        (``taskTypes``, ``seedContext``, …) to the snake_case shape
        used in :class:`acc.config.RoleDefinitionConfig`.
        """
        ...


class KubernetesCRDClient:
    """Production :class:`CRDClient` using the ``kubernetes`` Python lib.

    Lazy-imports ``kubernetes`` on first use so agents in
    ``role_source: files`` mode don't pay the import cost.
    """

    # CRD group / version / plural — matches operator/api/v1alpha1.
    _GROUP = "acc.redhat.io"
    _VERSION = "v1alpha1"
    _PLURAL = "agentcollectives"

    # Field translation: CRD camelCase → role.yaml snake_case.  Mirrors
    # operator/internal/filewatch/parser.go's onDiskRoleDefinition.
    _FIELD_MAP = {
        "purpose":            "purpose",
        "persona":            "persona",
        "taskTypes":          "task_types",
        "seedContext":        "seed_context",
        "allowedActions":     "allowed_actions",
        "categoryBOverrides": "category_b_overrides",
        "version":            "version",
    }

    def __init__(self, kube_config_path: Optional[str] = None) -> None:
        self._kube_config_path = kube_config_path
        self._api: Any = None  # kubernetes.client.CustomObjectsApi

    def _ensure_api(self) -> None:
        if self._api is not None:
            return
        try:
            from kubernetes import client, config  # noqa: PLC0415
        except ImportError as exc:
            raise RuntimeError(
                "kubernetes Python library is required for "
                "role_source=crd|mirror but is not installed.  "
                "Install with `pip install kubernetes` or switch "
                "role_source back to 'files' in acc-config.yaml."
            ) from exc

        # Prefer in-cluster config (pods running under the operator),
        # fall back to kubeconfig (laptop dev).
        try:
            config.load_incluster_config()
            logger.debug("KubernetesCRDClient: loaded in-cluster config")
        except Exception:
            try:
                config.load_kube_config(config_file=self._kube_config_path)
                logger.debug("KubernetesCRDClient: loaded kubeconfig")
            except Exception as exc:
                raise RuntimeError(
                    f"failed to load kubernetes config (incluster + kubeconfig): {exc}"
                ) from exc

        self._api = client.CustomObjectsApi()

    def list_collectives(self, namespace: str) -> list[dict[str, Any]]:
        self._ensure_api()
        try:
            response = self._api.list_namespaced_custom_object(
                group=self._GROUP,
                version=self._VERSION,
                namespace=namespace,
                plural=self._PLURAL,
            )
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                "KubernetesCRDClient: list failed in %s: %s",
                namespace, exc,
            )
            return []

        out: list[dict[str, Any]] = []
        for item in response.get("items", []):
            name = item.get("metadata", {}).get("name", "")
            if not name:
                continue
            spec = item.get("spec", {}) or {}
            rd_raw = spec.get("roleDefinition")
            if not rd_raw:
                out.append({"name": name, "role_definition": None})
                continue
            # CamelCase → snake_case translation.
            translated: dict[str, Any] = {}
            for camel, snake in self._FIELD_MAP.items():
                if camel in rd_raw:
                    translated[snake] = rd_raw[camel]
            out.append({"name": name, "role_definition": translated})
        return out


class RoleCRDProjector:
    """Polls the K8s API and writes ``roles/<id>/role.yaml`` files.

    Args:
        roles_root: Directory where projected files land.  Same path
            the agent's :class:`acc.role_loader.RoleLoader` reads from
            — the loader's existing file-watcher picks up the writes
            automatically.
        namespace: K8s namespace where AgentCollective resources live.
        client: :class:`CRDClient` impl.  Tests inject a fake; production
            constructs a :class:`KubernetesCRDClient`.
        poll_interval_s: Seconds between API polls.  Default 30.
    """

    def __init__(
        self,
        roles_root: str | Path,
        namespace: str,
        client: CRDClient,
        poll_interval_s: float = 30.0,
    ) -> None:
        self._roles_root = Path(roles_root)
        self._namespace = namespace
        self._client = client
        self._poll_interval_s = poll_interval_s
        self._task: Optional[asyncio.Task[None]] = None
        # Track the last canonical YAML we wrote per role so we can
        # short-circuit no-op rewrites without re-reading every poll.
        self._last_written: dict[str, str] = {}

    async def start(self) -> None:
        """Begin polling.  Safe to call multiple times."""
        if self._task is not None:
            return
        self._roles_root.mkdir(parents=True, exist_ok=True)
        self._task = asyncio.create_task(
            self._poll_loop(),
            name="role-crd-projector",
        )
        logger.info(
            "RoleCRDProjector: started (namespace=%s, interval=%.1fs, root=%s)",
            self._namespace, self._poll_interval_s, self._roles_root,
        )

    async def stop(self) -> None:
        """Cancel the polling task if running."""
        if self._task is None:
            return
        self._task.cancel()
        try:
            await self._task
        except asyncio.CancelledError:
            pass
        self._task = None

    async def project_once(self) -> int:
        """Run one polling cycle.  Returns the number of files written.

        Exposed publicly so the operator's startup sweep (and tests)
        can trigger a synchronous projection without waiting for the
        next poll tick.
        """
        try:
            collectives = self._client.list_collectives(self._namespace)
        except Exception as exc:  # noqa: BLE001
            logger.warning("RoleCRDProjector: list failed: %s", exc)
            return 0
        written = 0
        for item in collectives:
            name = item.get("name", "")
            rd = item.get("role_definition")
            if not name or not rd:
                continue
            if self.project_one(name, rd):
                written += 1
        return written

    def project_one(self, role_id: str, role_definition: dict[str, Any]) -> bool:
        """Project a single role's CRD spec to disk.

        Returns True when the file was actually written, False when
        the existing content already matched (idempotent no-op).
        """
        target_dir = self._roles_root / role_id
        target_path = target_dir / "role.yaml"

        # Strip empty / None values so we don't write noise.
        cleaned = {k: v for k, v in role_definition.items() if v is not None}
        if not cleaned:
            logger.debug(
                "RoleCRDProjector: empty role_definition for %s — skipping",
                role_id,
            )
            return False

        body = yaml.safe_dump(
            {"role_definition": cleaned},
            sort_keys=False,
            default_flow_style=False,
        )
        if not body.endswith("\n"):
            body += "\n"

        # Short-circuit: if we wrote this exact body last cycle, skip.
        if self._last_written.get(role_id) == body:
            return False

        # Second short-circuit: if the on-disk file already matches
        # (e.g. operator restart, file present from a previous run),
        # skip + remember.
        if target_path.exists():
            try:
                existing = target_path.read_text(encoding="utf-8")
                # Strip the sentinel header before comparing — the
                # timestamp inside the header changes every cycle and
                # we don't want that to count as a real diff.
                existing_body = _strip_sentinel(existing)
                if existing_body == body:
                    self._last_written[role_id] = body
                    return False
            except OSError:
                pass  # fall through to write

        target_dir.mkdir(parents=True, exist_ok=True)
        header = _SENTINEL_HEADER.format(
            namespace=self._namespace,
            name=role_id,
            ts=_utcnow_iso(),
        )
        # Atomic write via temp file + rename, so the agent's file
        # watcher never reads a half-written file.
        tmp_path = target_path.with_suffix(".yaml.tmp")
        tmp_path.write_text(header + body, encoding="utf-8")
        os.replace(tmp_path, target_path)
        self._last_written[role_id] = body
        logger.info(
            "RoleCRDProjector: wrote %s (CRD %s/%s)",
            target_path, self._namespace, role_id,
        )
        return True

    async def _poll_loop(self) -> None:
        while True:
            try:
                await self.project_once()
            except Exception as exc:  # noqa: BLE001
                logger.exception("RoleCRDProjector: poll failed: %s", exc)
            try:
                await asyncio.sleep(self._poll_interval_s)
            except asyncio.CancelledError:
                raise


def _strip_sentinel(content: str) -> str:
    """Return *content* with any leading ``# ...`` comment lines removed.

    Used by :meth:`RoleCRDProjector.project_one` to compare on-disk
    payload (which carries a sentinel header with a timestamp) against
    the freshly-rendered body (no header yet).
    """
    out: list[str] = []
    in_header = True
    for line in content.splitlines(keepends=True):
        if in_header:
            stripped = line.lstrip()
            if stripped.startswith("#") or stripped == "" or stripped == "\n":
                continue
            in_header = False
        out.append(line)
    return "".join(out)
