apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acc-hub-blobs
  namespace: acc-hub
  labels:
    app.kubernetes.io/name: acc-hub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
