# regulatory_layer/category_c/adaptive_rhoai.rego
# ==========================================================================
# ACC Adaptive Learned Rules — Category C (AUTO-GENERATED)
# ==========================================================================
#
# !! AUTO-GENERATED — DO NOT EDIT MANUALLY !!
#
# These rules are generated by the cognitive core's ICL consolidation
# pipeline. The arbiter signs the bundle manifest with its Ed25519 key
# before the OPA bundle server will serve this fragment.
#
# Levin mapping: These are the "cognitive" layer of the TAME spectrum —
# the highest persuadability level. Like epigenetic modifications that
# arise from experience and alter gene expression without changing DNA.
# Category C rules alter agent behavior without touching Category A
# constitutional rules.
#
# Each rule includes:
#   - Auto-generated ID with date stamp
#   - Source episode(s) that triggered the pattern
#   - Context description of the observed pattern
#   - Confidence score (must exceed icl_confidence_threshold from Cat-B)
#
# Arbiter signature: <base64 Ed25519 sig>
# Bundle signed at: 2026-04-03T10:15:00Z
#
# Version: 0.2.0
# Date:    2026-04-03
# ==========================================================================

package acc.membrane.adaptive

import future.keywords.if

# --------------------------------------------------------------------------
# C-AUTO-20260402-001 (carried from v0.1.0)
# --------------------------------------------------------------------------
# Source:     ICL episode ep_7f3a4b
# Context:   PDF documents > 10MB consistently cause RESOURCE_EXHAUSTION
#            in ingester agents. Allow large PDFs only when the agent has
#            sufficient resource headroom (> 40% available).
# Confidence: 0.87
# Pattern:   Resource-based task gating
#
# Levin analog: A cell under metabolic stress reduces its uptake of
#               large molecules to prevent lysis.
# --------------------------------------------------------------------------

allow_pdf_task if {
    input.task.document_type == "pdf"
    to_number(input.task.estimated_size_mb) <= 10
}

allow_pdf_task if {
    input.task.document_type == "pdf"
    to_number(input.task.estimated_size_mb) > 10
    input.agent.resource_headroom > 0.4
}

# --------------------------------------------------------------------------
# C-AUTO-20260403-001
# --------------------------------------------------------------------------
# Source:     ICL episodes ep_a1b2c3, ep_d4e5f6, ep_g7h8i9
# Context:   Analysis tasks on financial reports take 3x longer than
#            other document types. Analysts with health_score < 0.8
#            fail 72% of financial report tasks. Route financial reports
#            only to healthy analysts.
# Confidence: 0.91
# Pattern:   Role-health correlation gating
#
# Levin analog: Only cells with sufficient bioelectric potential can
#               participate in complex morphogenetic tasks. Weakened
#               cells are excluded from demanding tissue operations.
# --------------------------------------------------------------------------

allow_financial_analysis if {
    input.task.document_category == "financial_report"
    input.agent.health_score >= 0.8
    input.agent.role == "analyst"
}

allow_financial_analysis if {
    input.task.document_category != "financial_report"
}

# --------------------------------------------------------------------------
# C-AUTO-20260403-002
# --------------------------------------------------------------------------
# Source:     ICL episodes ep_j1k2l3, ep_m4n5o6
# Context:   When vLLM queue depth exceeds 8 on RHOAI, response latency
#            spikes above 10s causing task timeouts. Defer non-urgent
#            tasks when queue is saturated. Only high-priority tasks
#            (priority >= 0.8) proceed under load.
# Confidence: 0.84
# Pattern:   Infrastructure-aware throttling
#
# Levin analog: Under tissue-level stress (e.g., inflammation), cells
#               prioritize essential signaling and defer non-critical
#               metabolic processes.
# --------------------------------------------------------------------------

allow_llm_call_under_load if {
    input.deploy_mode != "rhoai"
}

allow_llm_call_under_load if {
    input.deploy_mode == "rhoai"
    input.vllm_queue_depth <= 8
}

allow_llm_call_under_load if {
    input.deploy_mode == "rhoai"
    input.vllm_queue_depth > 8
    input.task.priority >= 0.8
}

# --------------------------------------------------------------------------
# C-AUTO-20260403-003
# --------------------------------------------------------------------------
# Source:     ICL episodes ep_p7q8r9 (10-episode cluster)
# Context:   Memory sync operations during peak hours (09:00-17:00 UTC)
#            on RHOAI compete with active task processing for network
#            and Redis bandwidth. Batch COLLECTIVE_CONSOLIDATION syncs
#            to off-peak windows unless explicitly marked urgent.
# Confidence: 0.78
# Pattern:   Time-based scheduling optimization
#
# Levin analog: Circadian rhythms in biological tissues — certain
#               maintenance processes (DNA repair, cell division) are
#               scheduled for low-activity periods to avoid interference
#               with active function.
# --------------------------------------------------------------------------

allow_bulk_sync if {
    input.signal.payload.sync_type != "COLLECTIVE_CONSOLIDATION"
}

allow_bulk_sync if {
    input.signal.payload.sync_type == "COLLECTIVE_CONSOLIDATION"
    not is_peak_hours(input.current_hour_utc)
}

allow_bulk_sync if {
    input.signal.payload.sync_type == "COLLECTIVE_CONSOLIDATION"
    is_peak_hours(input.current_hour_utc)
    input.signal.payload.urgent == true
}

is_peak_hours(hour) if {
    hour >= 9
    hour <= 17
}
