#!/usr/bin/env python3
"""Generate ``acc/pkg/data/builtin_catalog.yaml`` from the bundled family packs.

The built-in catalog gives the Marketplace + Catalogs TUI panes real content on
day 0, offline — the role families that ship with ACC.  The catalog *index*
(``CatalogIndexEntry``) is deliberately minimal (name/version/sha only), so the
rich per-package metadata the panes show — description, roles, skill + MCP
counts — is generated HERE from each pack's ``accpkg.yaml`` manifest and
committed as package data.

This same file is the source published to the ``acc-ecosystem`` Pages catalog
(build local first → export), so it stays the one source of truth.

Usage::

    python -m tools.gen_builtin_catalog            # src = tests/fixtures/packs
    python -m tools.gen_builtin_catalog --src dist --check
"""

from __future__ import annotations

import argparse
import io
import sys
import tarfile
from pathlib import Path

import yaml

_REPO = Path(__file__).resolve().parent.parent
_DEFAULT_SRC = _REPO / "tests" / "fixtures" / "packs"
_OUT = _REPO / "acc" / "pkg" / "data" / "builtin_catalog.yaml"

# Catalog-level trust identity.  The packs' manifests don't carry tier/signer
# (those are a property of the catalog that advertises them); ACC's own packs
# are trusted + published under the acc-ecosystem GitHub OIDC identity.
_CATALOG = {
    "id": "acc-builtin",
    "name": "ACC Built-in Roles",
    "description": "Role families that ship with ACC — browse + install offline from day 0.",
    "tier": "trusted",
    "url": "https://flg77.github.io/acc-ecosystem",
    "oidc_issuer": "https://token.actions.githubusercontent.com",
    "signer": "acc-ecosystem (github oidc)",
}

_HEADER = (
    "# Built-in day-0 catalog — the ACC role families bundled with the runtime.\n"
    "#\n"
    "# GENERATED by tools/gen_builtin_catalog.py from each pack's accpkg.yaml —\n"
    "# do NOT hand-edit.  Gives the Marketplace + Catalogs TUI panes real content\n"
    "# on day 0, offline.  This same metadata is the source published to the\n"
    "# acc-ecosystem Pages catalog (build local first → export).\n"
)


def _manifest_of(accpkg: Path) -> dict:
    """Extract + parse the ``accpkg.yaml`` manifest from a ``.accpkg`` tarball."""
    with tarfile.open(accpkg, "r:gz") as tar:
        member = tar.extractfile("accpkg.yaml")
        if member is None:
            raise ValueError(f"{accpkg.name}: no accpkg.yaml in tarball")
        return yaml.safe_load(io.TextIOWrapper(member, encoding="utf-8")) or {}


def _package_entry(manifest: dict) -> dict:
    roles = [r["name"] for r in manifest.get("roles", []) if r.get("name")]
    skills = [s["name"] for s in manifest.get("skills", []) if s.get("name")]
    mcps = [m["name"] for m in manifest.get("mcps", []) if m.get("name")]
    return {
        "name": manifest["name"],
        "version": str(manifest["version"]),
        "description": manifest.get("description", "") or "",
        "n_roles": len(roles),
        "n_skills": len(skills),
        "n_mcps": len(mcps),
        "roles": roles,
        "skills": skills,
        "mcps": mcps,
    }


def build(src: Path) -> dict:
    packs = sorted(src.glob("*.accpkg"))
    if not packs:
        raise SystemExit(f"no .accpkg packs found in {src}")
    packages = [_package_entry(_manifest_of(p)) for p in packs]
    packages.sort(key=lambda e: e["name"])
    return {"schema_version": 1, "catalog": _CATALOG, "packages": packages}


def render(doc: dict) -> str:
    return _HEADER + yaml.safe_dump(
        doc, sort_keys=False, default_flow_style=False, allow_unicode=True, width=100
    )


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--src", type=Path, default=_DEFAULT_SRC,
                    help="dir of .accpkg packs (default: tests/fixtures/packs)")
    ap.add_argument("--out", type=Path, default=_OUT)
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed file is stale (CI guard)")
    args = ap.parse_args(argv)

    text = render(build(args.src))
    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        if current != text:
            print(f"STALE: {args.out} differs from generated — re-run gen_builtin_catalog",
                  file=sys.stderr)
            return 1
        print(f"OK: {args.out} is up to date")
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    doc = yaml.safe_load(text)
    print(f"wrote {args.out} — {len(doc['packages'])} packages, "
          f"{sum(p['n_roles'] for p in doc['packages'])} roles, "
          f"{sum(p['n_skills'] for p in doc['packages'])} skills, "
          f"{sum(p['n_mcps'] for p in doc['packages'])} mcps")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
