"""Built-in day-0 catalog — the ACC role families bundled with the runtime.

Reads ``acc/pkg/data/builtin_catalog.yaml`` (generated by
``tools/gen_builtin_catalog.py`` from the pack manifests, committed as package
data) so the Marketplace + Catalogs TUI panes show real content on day 0,
offline — no configured catalog, no network needed.

The generic catalog *index* (:class:`acc.pkg.catalog.CatalogIndexEntry`) is
deliberately minimal (name/version/sha), so the rich per-package metadata the
panes display — description, roles, skill + MCP counts — lives here.  This same
metadata is the source published to the acc-ecosystem Pages catalog.
"""

from __future__ import annotations

import logging
from importlib import resources
from pathlib import Path

import yaml
from pydantic import BaseModel, Field

logger = logging.getLogger("acc.pkg.builtin_catalog")

_DATA_PACKAGE = "acc.pkg.data"
_DATA_FILE = "builtin_catalog.yaml"


class BuiltinPackage(BaseModel):
    """One bundled family pack, with the counts the Marketplace shows."""

    name: str
    version: str = "0.0.0"
    description: str = ""
    n_roles: int = 0
    n_skills: int = 0
    n_mcps: int = 0
    roles: list[str] = Field(default_factory=list)
    skills: list[str] = Field(default_factory=list)
    mcps: list[str] = Field(default_factory=list)


class BuiltinCatalog(BaseModel):
    """The built-in catalog header + its packages."""

    id: str = "acc-builtin"
    name: str = "ACC Built-in Roles"
    description: str = ""
    tier: str = "trusted"
    url: str = ""
    oidc_issuer: str = ""
    signer: str = ""
    packages: list[BuiltinPackage] = Field(default_factory=list)

    def all_roles(self) -> list[str]:
        """Sorted, de-duplicated union of every role across the packs — the
        Catalogs pane's ``roles`` column."""
        seen: set[str] = set()
        for pkg in self.packages:
            seen.update(pkg.roles)
        return sorted(seen)


def _raw() -> dict:
    """Load the raw YAML, best-effort.  Package resource first (installed), then
    a repo-relative fallback (editable checkout without a reinstall)."""
    try:
        text = (
            resources.files(_DATA_PACKAGE)
            .joinpath(_DATA_FILE)
            .read_text(encoding="utf-8")
        )
        return yaml.safe_load(text) or {}
    except (FileNotFoundError, ModuleNotFoundError, OSError):
        pass
    here = Path(__file__).resolve().parent / "data" / _DATA_FILE
    if here.is_file():
        try:
            return yaml.safe_load(here.read_text(encoding="utf-8")) or {}
        except OSError:
            pass
    return {}


def load_builtin_catalog() -> BuiltinCatalog:
    """Return the built-in catalog (empty catalog if the data file is absent —
    never raises on the TUI render path)."""
    raw = _raw()
    if not raw:
        return BuiltinCatalog(packages=[])
    header = dict(raw.get("catalog", {}) or {})
    header["packages"] = raw.get("packages", []) or []
    try:
        return BuiltinCatalog.model_validate(header)
    except Exception:
        logger.exception("builtin_catalog: invalid %s", _DATA_FILE)
        return BuiltinCatalog(packages=[])
